// src/pages/About.tsx
export default function About() {
  return (
    <div className="container">
      <main className="main">
        <div className="about-content">
          <section className="about-section">
            <h1>About Me</h1>
            <p>
              I'm Bryan Tao Long, a passionate developer who enjoys creating software solutions
              and sharing knowledge through writing and teaching.
            </p>
            <p>
              This personal website serves as a space for my thoughts, projects, and learning journey.
            </p>
          </section>

          <section className="about-section">
            <h2>Skills & Interests</h2>
            <p>
              I'm interested in various technologies and constantly learning new things.
              My focus areas include web development, software engineering, and creating
              minimalistic user experiences.
            </p>
          </section>

          <section className="about-section">
            <h2>Contact</h2>
            <p>
              Feel free to reach out to me through email or connect with me on social platforms.
            </p>
          </section>
        </div>
      </main>
    </div>
  )
}

// src/views/About.vue
<template>
  <div class="container">
    <main class="main">
      <div class="about-content">
        <section class="about-section">
          <h1>About Me</h1>
          <p>
            I'm Bryan Tao Long, a passionate developer who enjoys creating software solutions
            and sharing knowledge through writing and teaching.
          </p>
          <p>
            This personal website serves as a space for my thoughts, projects, and learning journey.
          </p>
        </section>

        <section class="about-section">
          <h2>Skills & Interests</h2>
          <p>
            I'm interested in various technologies and constantly learning new things.
            My focus areas include web development, software engineering, and creating
            minimalistic user experiences.
          </p>
        </section>

        <section class="about-section">
          <h2>Contact</h2>
          <p>
            Feel free to reach out to me through email or connect with me on social platforms.
          </p>
        </section>
      </div>
    </main>
  </div>
</template>

<script setup lang="ts">
</script>
