// src/pages/Post.tsx
import { useState, useEffect } from 'react'
import { useParams } from 'react-router-dom'
import { usePosts, type Post } from '../contexts/PostsContext'

function formatDate(dateString: string): string {
  const date = new Date(dateString)
  return date.toISOString().split('T')[0]
}

export default function PostPage() {
  const { filename } = useParams<{ filename: string }>()
  const { getPost } = usePosts()
  const [post, setPost] = useState<Post | null>(null)
  const [error, setError] = useState<string | null>(null)

  useEffect(() => {
    if (!filename) return
    const fn = filename
    let cancelled = false

    async function fetchPost() {
      try {
        const result = await getPost(fn)
        if (!cancelled) {
          if (result) {
            setPost(result)
          } else {
            setError(`Post "${fn}" not found.`)
          }
        }
      } catch (err) {
        if (!cancelled) {
          setError(`Error loading post: ${err instanceof Error ? err.message : String(err)}`)
        }
      }
    }

    fetchPost()
    return () => { cancelled = true }
  }, [filename, getPost])

  if (post) {
    return (
      <div className="container">
        <main className="main">
          <div className="post">
            <header className="post-header">
              <h1 className="post-title">{post.title || filename}</h1>
              <div className="post-meta">
                <span>{formatDate(post.date)}</span>
              </div>
              {post.tags && post.tags.length > 0 && (
                <div className="post-tags">
                  {post.tags.map(tag => (
                    <span key={tag} className="tag">{tag}</span>
                  ))}
                </div>
              )}
              {post.summary && (
                <div className="post-summary">{post.summary}</div>
              )}
            </header>
            <article className="post-content" dangerouslySetInnerHTML={{ __html: post.content }} />
          </div>
        </main>
      </div>
    )
  }

  if (error) {
    return (
      <div className="container">
        <main className="main">
          <div className="error">{error}</div>
        </main>
      </div>
    )
  }

  return (
    <div className="container">
      <main className="main">
        <div className="loading">Loading post...</div>
      </main>
    </div>
  )
}

// src/views/Post.vue
<template>
  <div class="container">
    <main class="main">
      <div class="post" v-if="post">
        <header class="post-header">
          <h1 class="post-title">{{ post.title || filename }}</h1>
          <div class="post-meta">
            <span>{{ formatDate(post.date) }}</span>
          </div>
        </header>
        <article class="post-content" v-html="post.content"></article>
      </div>
      <div v-else-if="error" class="error">
        {{ error }}
      </div>
      <div v-else class="loading">
        Loading post...
      </div>
    </main>
  </div>
</template>

<script setup>
import { ref, onMounted } from 'vue'
import { useRoute } from 'vue-router'
import { usePosts } from '../composables/usePosts'

const route = useRoute()
const { getPost } = usePosts()

const post = ref(null)
const error = ref(null)
const filename = ref(route.params.filename)

const formatDate = (dateString) => {
  const date = new Date(dateString)
  return date.toISOString().split('T')[0]
}

onMounted(async () => {
  try {
    post.value = await getPost(filename.value)
    if (!post.value) {
      error.value = `Post "${filename.value}" not found.`
    }
  } catch (err) {
    error.value = `Error loading post: ${err.message}`
  }
})
</script>

<style scoped>
/* Styles are imported globally from simple.css */
</style>
